include ../config/config.mk

COMP := nicUtil
COMP_NAME := "NIC Util Java Library"
TITLE := "NIC Util Java Library Implementation Details"
INPUT := \. \.\./src/main/java/tmt/nic/util

all:
	$(call make_doxygen_doc)

clean:
	$(call make_doxygen_clean)

