include ../config/config.mk

COMP := nicUtil
COMP_NAME := "nic.util"
TITLE := "nic.util Java utility library"
INPUT := \. \.\./src/main/java/nic/util \.\./src/test

all:
	$(call make_doxygen_doc)

clean:
	$(call make_doxygen_clean)

