include ../../util/config/config.mk

COMP := javaComp
COMP_NAME := Java Component 
TITLE := "Java Component Tech Note"
DOC_NUM := "TMT.AOS.TEC.XX.XXX"
INPUT := \.

all:
	$(call make_doxygen_techNote_comp)

clean:
	$(call make_doxygen_clean)

