include ../../util/config/config.mk

COMP := javaComp
COMP_NAME := "Java Component"
TITLE := "Java Component Implementation Details"
INPUT := \. \.\./src 

all:
	$(call make_doxygen_doc)

clean:
	$(call make_doxygen_clean)

