include ../../util/config/config.mk

COMP := topLevel
COMP_NAME := Top Level 
TITLE := "Template Top Level Architecture Tech Note"
DOC_NUM := "TMT.AOS.TEC.XX.XXX.DRF01"
INPUT := \. 

all:
	$(call make_doxygen_techNote_comp)

clean:
	$(call make_doxygen_clean)

