include ../../util/config/config.mk

COMP := cComp
COMP_NAME := C Component 
TITLE := "C/C++ Component Tech Note"
DOC_NUM := "TMT.AOS.TEC.XX.XXX"
INPUT := \.

all:
	$(call make_doxygen_techNote_comp)

clean:
	$(call make_doxygen_clean)

