include ../../util/config/config.mk

COMP := cComp
COMP_NAME := "C Component"
TITLE := "C/C++ Component Implementation Details"
INPUT := \. \.\./h \.\./src 

all:
	$(call make_doxygen_doc)

clean:
	$(call make_doxygen_clean)

